### ISSUE TITLE
change the value displayed

### ISSUE THREAD

**Issue by geekyaleks** [edgar-zigis/GaugeSlider#1]
Hi there,

is there a way to display something other than a temperature in your gauge.  It shows degrees with the little 0 .  I would like to display something like -76dB for example...

Thanks Alex.

**Comment by edgar-zigis** [comment]
Hey @geekyaleks, sorry for late response, but yes, there is a `unit` parameter which you can change to any unit. More about every parameter in the README page.

**Comment by geekyaleks** [comment]
Thanks for the reply!!
